apiVersion: v1
kind: SvcRoute
metadata:
  name: fusingtest 
  namespace: svcrouter-test1
spec:
  global: true
  rule:
    type: Percentage
  to:
  - balance: roundrobin
    kind: Service
    name: testapi-v-1
    rule: 70
  - balance: roundrobin
    kind: Service
    name: testapi-v-2
    rule: 20 
  - balance: roundrobin
    kind: Service
    name: testapi-v-3
    rule: 10 
