apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: JiangWentianLocalVM 
  labels:
    app: testapi 
  name: testapi 
  namespace: svcrouter-test1
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: testapi-v1
  sessionAffinity: None
  type: ClusterIP
