apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: JiangWentianLocalVM
  labels:
    app: testapi-v-1
  name: testapi-v-1
  namespace: svcrouter-test1
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: testapi-v-1
  sessionAffinity: None
  type: ClusterIP

